import "./globals.css";
import { Poppins } from "next/font/google";
import { generalsans } from "./font";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "MITRA SOLUSI WICAKSANA",
  description: "Generated by create next app",
  link,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={generalsans.className}>{children}</body>
    </html>
  );
}
